### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by xsIceman** [spavkov/BooleanLogicExpressionParser#3]
will it be The MIT License?

**Comment by Mannheimd** [comment]
@spavkov Seconding this, your implementation is awesome and I'd like to use it in a project but obviously not without your permission!

Would you be happy for me to re-use this?

**Comment by spavkov** [comment]
Feel free to use as needed. I will add the least restrictive license i will find. Thanks for pointing it out!

**Comment by spavkov** [comment]
Added MIT license
